// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD1Qf9XOzuIr7QNpeNBFF1E7tAwnPYdZk',
    appId: '1:1053697304542:android:584f0e29a69487bd859f4f',
    messagingSenderId: '1053697304542',
    projectId: 'stocks-240',
    storageBucket: 'stocks-240.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpru2u0TJ8_kQJ2Gq5X0syJV0AbJO0bFg',
    appId: '1:1053697304542:ios:e38d6d86f291dcd0859f4f',
    messagingSenderId: '1053697304542',
    projectId: 'stocks-240',
    storageBucket: 'stocks-240.appspot.com',
    androidClientId: '1053697304542-54i494l62q3vflri43eoo7jociib3dkn.apps.googleusercontent.com',
    iosClientId: '1053697304542-3qco730gtnr7a04m0p4ed0ajpd62cfnc.apps.googleusercontent.com',
    iosBundleId: 'com.example.stocks',
  );
}
